version: '3.1'

services:
  frontend:
    build: frontend/
    depends_on:
      - 'database'
    ports:
      - '3000:3000'

  backend:
    build: backend/
    depends_on:
      - 'database'
    ports: 
      - '8080:8080'
    command: sh -c "npx knex migrate:latest && npx knex seed:run && npm start"

  database:
    image: postgres
    volumes:
      - ./backend/database:/var/lib/postgesql/data
    restart: always
    environment:
      POSTGRES_DB: mycro_brewery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - '5432:5432'

volumes:
  database:


    
